services:
  mysqldb:
    image: mysql
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'cityForCitizens'
      MYSQL_USER: root
      MYSQL_PASSWORD: 1488
      MYSQL_ROOT_PASSWORD: 1488
      MYSQL_ROOT_HOST: '%'
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  app:
    container_name: appcontainer
    build: .
    image: city-for-citizens-backend:0.0.1.RELEASE
    command: npm run setup
    env_file:
      - .env
    ports:
      - 4000:4000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3307
      DB_NAME: cityForCitizens
      DB_USER: root
      DB_PASSWORD: 1488
      SERVICE_TAGS: prod
      SERVICE_NAME: app
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  db: {}
